// ╭──────────────────────────────────────────────────────────────────────────╮
// │                                                                          │
// │   G R E E T I N G   P R E V I E W                                        │
// │   animated preview of a greeting scene                                   │
// │                                                                          │
// │   github.com/andreumassanet/impasto                                      │
// │                                                                          │
// ╰──────────────────────────────────────────────────────────────────────────╯

import QtQuick

import "../services"

// Plays the `fa` greeting GIF generated by the palette push, scaled by 0.4
// without smoothing: the file is drawn at 5 px per pixel, so each lands on
// exactly 2 screen pixels.
//
// `version` is the stamp greeting.py writes once a full set is rendered, so
// tiles reload after a palette change only when the new scenes exist.
Item {
    id: root

    // A row id from `ThemeService.greetings`.
    property string scene: "lava"
    property string version: ""

    // · source size, and screen pixels per source pixel
    readonly property int drawingWidth: 54
    readonly property int drawingHeight: 60
    readonly property int pixel: 2

    // "random" cycles through the scenes.
    readonly property var pool: ThemeService.greetings
        .filter(row => row.id !== "random").map(row => row.id)
    property int pass: 0
    readonly property string drawn: root.scene === "random"
        ? root.pool[root.pass % root.pool.length] : root.scene

    implicitWidth: root.drawingWidth * root.pixel
    implicitHeight: root.drawingHeight * root.pixel

    AnimatedImage {
        anchors.centerIn: parent
        width: root.implicitWidth
        height: root.implicitHeight
        source: `file://${SettingsService.stateDirectory}/greeting-${root.drawn}.gif?${root.version}`
        smooth: false
        cache: false
        playing: root.visible
    }

    // · how long "random" shows each scene. Not a motion token, since the
    //   Motion setting can scale those to zero.
    readonly property int dwell: 2400

    Timer {
        running: root.scene === "random" && root.visible
        interval: root.dwell
        repeat: true
        onTriggered: root.pass += 1
    }
}
